/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'rich_chat_copilot';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String IC_BACK_ARROW = 'assets/images/ic_back_arrow.svg';
  static const String IC_CAMERA = 'assets/images/ic_camera.svg';
  static const String IC_CANCEL = 'assets/images/ic_cancel.svg';
  static const String IC_SUCCESS = 'assets/images/ic_success.svg';
  static const String LOG2 = 'assets/images/log2.json';
  static const String USER = 'assets/images/user.jpg';
}
