/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String ALMARAI_BOLD = 'Almarai-Bold';
  static const String ALMARAI_EXTRABOLD = 'Almarai-ExtraBold';
  static const String ALMARAI_LIGHT = 'Almarai-Light';
  static const String ALMARAI_REGULAR = 'Almarai-Regular';
  static const String MONTSERRAT_BOLD = 'Montserrat-Bold';
  static const String MONTSERRAT_MEDIUM = 'Montserrat-Medium';
  static const String MONTSERRAT_REGULAR = 'Montserrat-Regular';
  static const String MONTSERRAT_SEMIBOLD = 'Montserrat-SemiBold';
}
