/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class ImagePaths {
  static const String user = 'assets/images/user.jpg';
  static const String log1 = 'assets/images/log1.json';
  static const String log2 = 'assets/images/log2.json';
  static const String log3 = 'assets/images/log3.json';
  static const String mic = 'assets/images/mic.json';
  static const String icCancel = 'assets/images/ic_cancel.svg';
  static const String icSuccess = 'assets/images/ic_success.svg';
  static const String icCamera = 'assets/images/ic_camera.svg';
  static const String icGallery = 'assets/images/ic_gallary.svg';
  static const String icDelete = 'assets/images/ic_delete.svg';
  static const String icBackArrow = 'assets/images/ic_back_arrow.svg';
  static const String icPause = 'assets/images/ic_audio_pause.svg';
  static const String icVolume = 'assets/images/ic_volume.svg';
  static const String icVolumeMute = 'assets/images/ic_volumeoff.svg';
  static const String icPlay = 'assets/images/ic_audio_play.svg';
  static const String icClose = 'assets/images/ic_close.svg';
  static const String icFile = 'assets/images/ic_file.svg';
  static const String icMicrophone = 'assets/images/microphone.svg';
  static const String icVedio = 'assets/images/video.svg';
  static const String icStop = 'assets/images/ic_stop.svg';
}
