
/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class ImagePaths {
static const String user = 'assets/images/user.jpg';
static const String log1 = 'assets/images/log1.json';
static const String log2 = 'assets/images/log2.json';
static const String log3 = 'assets/images/log3.json';
static const String icCancel='assets/images/ic_cancel.svg';
static const String icSuccess='assets/images/ic_success.svg';
static const String icCamera='assets/images/ic_camera.svg';
static const String icGallery='assets/images/ic_gallary.svg';
static const String icDelete='assets/images/ic_delete.svg';
static const String icBackArrow='assets/images/ic_back_arrow.svg';
}
