// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJiKfK9k0gc7l0HbM2fyFRMmrwNpOPF8',
    appId: '1:127177945549:web:c3e5781859e57f6a3f1484',
    messagingSenderId: '127177945549',
    projectId: 'richchatspro',
    authDomain: 'richchatspro.firebaseapp.com',
    storageBucket: 'richchatspro.appspot.com',
    measurementId: 'G-ME8CCC1752',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC-r_4F_0xwJwmUl0vckTDRxwG2db2WhY',
    appId: '1:127177945549:android:3161c863f5c88fbc3f1484',
    messagingSenderId: '127177945549',
    projectId: 'richchatspro',
    storageBucket: 'richchatspro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUQ4vtKQENGpilkx4LfepPqxAbWjMg-sQ',
    appId: '1:127177945549:ios:0cbe0a2b497bcf033f1484',
    messagingSenderId: '127177945549',
    projectId: 'richchatspro',
    storageBucket: 'richchatspro.appspot.com',
    iosBundleId: 'com.example.richChatCopilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUQ4vtKQENGpilkx4LfepPqxAbWjMg-sQ',
    appId: '1:127177945549:ios:0cbe0a2b497bcf033f1484',
    messagingSenderId: '127177945549',
    projectId: 'richchatspro',
    storageBucket: 'richchatspro.appspot.com',
    iosBundleId: 'com.example.richChatCopilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAJiKfK9k0gc7l0HbM2fyFRMmrwNpOPF8',
    appId: '1:127177945549:web:089c3ba7dc3508603f1484',
    messagingSenderId: '127177945549',
    projectId: 'richchatspro',
    authDomain: 'richchatspro.firebaseapp.com',
    storageBucket: 'richchatspro.appspot.com',
    measurementId: 'G-TTS0QE4MLR',
  );
}
